[package]
name = "stewart"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
thunderdome.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
