[package]
name = "stewart"
version = "0.1.0"
edition = "2021"

[dependencies]
thunderdome.workspace = true
tracing.workspace = true
stewart-derive.workspace = true
value-bag = "0.1.0"

[dev-dependencies]
tracing-subscriber.workspace = true
