[package]
name = "stewart-scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
family.workspace = true
stewart.workspace = true
tracing.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
