[package]
name = "ptero-daicon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
daicon.workspace = true
stewart.workspace = true
stewart-utils.workspace = true
tracing.workspace = true
uuid.workspace = true
ptero-io.workspace = true
